package com.asoft.bazar.ui.theme.tokens

import androidx.compose.ui.graphics.Color

public class MyColors {
    companion object {
        val background = Color(0xFFFEF7FF)
        val error = Color(0xFFB3261E)
        val errorContainer = Color(0xFFF9DEDC)
        val inverseOnSurface = Color(0xFFF5EFF7)
        val inversePrimary = Color(0xFFD0BCFF)
        val inverseSurface = Color(0xFF322F35)
        val onBackground = Color(0xFF1D1B20)
        val onError = Color(0xFFFFFFFF)
        val onErrorContainer = Color(0xFF852221)
        val onPrimary = Color(0xFFFFFFFF)
        val onPrimaryContainer = Color(0xFF4F378A)
        val onPrimaryFixed = Color(0xFF21005D)
        val onPrimaryFixedDim = Color(0xFFD0BCFF)
        val onPrimaryFixedVariant = Color(0xFF4F378B)
        val onSecondary = Color(0xFFFFFFFF)
        val onSecondaryContainer = Color(0xFF4A4459)
        val onSecondaryFixed = Color(0xFF1D192B)
        val onSecondaryFixedVariant = Color(0xFF4A4458)
        val onSurface = Color(0xFF1D1B20)
        val onSurfaceVariant = Color(0xFF49454F)
        val onTertiary = Color(0xFFFFFFFF)
        val onTertiaryContainer = Color(0xFF633B48)
        val onTertiaryFixed = Color(0xFF31111D)
        val onTertiaryFixedVariant = Color(0xFF633B48)
        val outline = Color(0xFF79747E)
        val outlineVariant = Color(0xFFCAC4D0)
        val primary = Color(0xFF65558F)
        val primaryContainer = Color(0xFFEADDFF)
        val primaryFixed = Color(0xFFEADDFF)
        val secondary = Color(0xFF625B71)
        val secondaryContainer = Color(0xFFE8DEF8)
        val secondaryFixed = Color(0xFFE8DEF8)
        val secondaryFixedDim = Color(0xFFCCC2DC)
        val shadow = Color(0xFF000000)
        val surface = Color(0xFFFEF7FF)
        val surfaceBright = Color(0xFFFEF7FF)
        val surfaceContainer = Color(0xFFF3EDF7)
        val surfaceContainerHight = Color(0xFFECE6F0)
        val surfaceContainerHightest = Color(0xFFE6E0E9)
        val surfaceContainerLow = Color(0xFFF7F2FA)
        val surfaceContainerLowest = Color(0xFFFFFFFF)
        val surfaceDim = Color(0xFFDED8E1)
        val surfaceTint = Color(0xFF6750A4)
        val surfaceVariant = Color(0xFFE7E0EC)
        val tertiary = Color(0xFF7D5260)
        val tertiaryContainer = Color(0xFFFFD8E4)
        val tertiaryFixed = Color(0xFFFFD8E4)
        val tertiaryFixedDim = Color(0xFFEFB8C8)
    }
}